# @package _global_

rewards:
  set_reward: Q1_GK_LowRight2_Extend_v1
  set_reward_date: '20260808'
  only_positive_rewards: false
  reward_scales:
    q1_joint_position_tracking: 4.0
    q1_joint_velocity_tracking: 2.5
    q1_lower_body_joint_position_tracking: 2.0
    q1_lower_body_joint_velocity_tracking: 1.0
    q1_gk_dive_right_leg_position_tracking: 6.0
    q1_gk_dive_right_leg_velocity_tracking: 2.0
    q1_gk_dive_right_foot_position_tracking: 4.0
    teleop_body_position_extend: 2.0
    teleop_body_position_feet: 2.0
    teleop_body_rotation_extend: 0.3
    teleop_body_velocity_extend: 0.5
    teleop_body_ang_velocity_extend: 0.5
    penalty_action_rate: -0.3
    penalty_torques: -1.0e-06
    limits_torque: -0.1
    termination: -30.0
    penalty_feet_ori: 0.0
    penalty_slippage: -1.0
    feet_heading_alignment: 0.0
    teleop_joint_position: 0.0
  teleop_body_pos_lowerbody_weight: 1.1
  teleop_body_pos_upperbody_weight: 0.6
  reward_tracking_sigma:
    q1_joint_pos: 0.1
    q1_joint_vel: 1.5
    q1_lower_body_joint_pos: 0.05
    q1_lower_body_joint_vel: 1.0
    teleop_upper_body_pos: 0.03
    teleop_lower_body_pos: 0.05
    teleop_feet_pos: 0.05
    teleop_body_rot: 3.0
    teleop_body_vel: 1.0
    teleop_body_ang_vel: 1.0
    teleop_joint_pos: 0.5
    teleop_joint_vel: 0.5
    q1_gk_dive_right_leg_pos: 0.025
    q1_gk_dive_right_leg_vel: 1.0
    q1_gk_dive_right_foot_pos: 0.01
  reward_penalty_curriculum: false
  reward_initial_penalty_scale: 0.15
  reward_min_penalty_scale: 0.0
  reward_max_penalty_scale: 0.4
  reward_penalty_level_down_threshold: 40
  reward_penalty_level_up_threshold: 42
  reward_penalty_degree: 3.0e-06
  num_compute_average_epl: 10000
  reward_limit:
    soft_dof_pos_limit: 0.9
    soft_dof_vel_limit: 0.9
    soft_torque_limit: 0.9
    reward_limits_curriculum:
      soft_dof_pos_curriculum: false
      soft_dof_pos_initial_limit: 1.15
      soft_dof_pos_max_limit: 1.15
      soft_dof_pos_min_limit: 0.95
      soft_dof_pos_curriculum_degree: 2.5e-07
      soft_dof_pos_curriculum_level_down_threshold: 40
      soft_dof_pos_curriculum_level_up_threshold: 42
      soft_dof_vel_curriculum: false
      soft_dof_vel_initial_limit: 1.15
      soft_dof_vel_max_limit: 1.25
      soft_dof_vel_min_limit: 0.95
      soft_dof_vel_curriculum_degree: 2.5e-07
      soft_dof_vel_curriculum_level_down_threshold: 40
      soft_dof_vel_curriculum_level_up_threshold: 42
      soft_torque_curriculum: false
      soft_torque_initial_limit: 1.05
      soft_torque_max_limit: 1.15
      soft_torque_min_limit: 0.85
      soft_torque_curriculum_degree: 2.5e-05
      soft_torque_curriculum_level_down_threshold: 28
      soft_torque_curriculum_level_up_threshold: 42
  reward_penalty_reward_names:
  - penalty_torques
  - penalty_dof_acc
  - penalty_dof_vel
  - penalty_action_rate
  - limits_dof_pos
  - limits_dof_vel
  - limits_torque
  - feet_heading_alignment
  - penalty_feet_ori
  - penalty_slippage
  q1_gk_dive_phase:
    start: 0.1
    end: 0.35
    transition: 0.02
